### ISSUE TITLE
AttributeError: 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by LeeBinder** [brianc118/Google-Calendar-Undo-Import#7]
After logging into my main calendar in terminal by typing 0, ENTER, I get:

> Select calendar by typing in the index
0
Traceback (most recent call last):
  File "/Users/lee/gcal_undo_import.py", line 107, in <module>
    main(sys.argv)
  File "/Users/lee/gcal_undo_import.py", line 72, in main
    x = getUserInputIndex('\nSelect calendar by typing in the index', i)
  File "/Users/lee/gcal_undo_import.py", line 37, in getUserInputIndex
    if x.isdigit():
AttributeError: 'int' object has no attribute 'isdigit'

Is there anything I can or need to do (differently)?

macOS Mojave 10.14.6
Python 3.8.1

**Comment by mai2412** [comment]
I'll fix this!
